artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/compressive/Concrete_Data.xls
  local_data_file: artifacts/data_ingestion/data.xls
  unzip_dir: artifacts/data_ingestion
  ingested_data_train_dir: artifacts/data_ingestion/train
  ingested_data_test_dir: artifacts/data_ingestion/test

dat_validation:
  root_dir: artifacts/data_validation
  schema_dir: configs/schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  root_dir: artifacts/data_transformation
