columns:
  Cement: float64            
  Blast Furnace Slag: float64
  Fly Ash: float64             
  Water: float64               
  Superplasticizer: float64   
  Coarse Aggregate: float64   
  Fine Aggregate: float64 
  Age: int